version: '3.5'
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@database:5432/blog
      CONFIG_NAME: DevConfig
    volumes:
    - ./blog:/app/blog
    ports:
      - 8080:5000
    depends_on:
      - database
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  pgdata:
