"""empty message

Revision ID: 290d98b400b4
Revises: f9bd6ab9de9f
Create Date: 2023-04-24 22:22:12.849364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290d98b400b4'
down_revision = 'f9bd6ab9de9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
